### PR TITLE
[youtube] Fix #29 YoutubePlaylistsIE

### LINKED ISSUE #29: [youtube] playlists page stopped working
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.youtube.com/user/TheLinuxFoundation/playlists
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/user/TheLinuxFoundation/playlists']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.9.0 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlists] TheLinuxFoundation: Downloading webpage
[download] Downloading playlist: The Linux Foundation
[youtube:playlists] playlist The Linux Foundation: Downloading 0 videos
[download] Finished downloading playlist: The Linux Foundation
```
See: **Downloading 0 videos**

### PR DESCRIPTION
**Pull request by ZenulAbidin**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This fixes #29 by replacing the regexes responsible for matching the ID of the next page of playlists.

### CODE REVIEW

**Comment by ZenulAbidin** [comment]
Could I get write access so future commits can be merged faster?

**Comment by l1ving** [comment]
No, it hasn't even been 15 hours. I haven't had time to review as your pull was made on a Sunday evening and I have classes in the mornings. I'll review this in a few hours

**Comment by l1ving** [comment]
```
youtube-dl -v https://www.youtube.com/user/TheLinuxFoundation/playlists
```
I tested your pr with this command, it found 14 videos but downloaded none. https://pastebin.com/raw/yBUXz0UU

**Comment by ZenulAbidin** [comment]
@l1ving Suddenly videos don't download with youtube-dlc either.

https://github.com/blackjack4494/yt-dlc/issues/148

Looks like it's a major problem now: https://www.reddit.com/r/youtubedl/comments/jr56fs/yourubedl_sees_all_channel_links_as_empty/

They were working fine last night. It would need to be resolved in another PR.

**Comment by bubonic** [comment]
Not sure what youtube-dl uses, but here is my temporary fix:

```

import dryscrape
from bs4 import BeautifulSoup
import sys

URL = sys.argv[1]
MetaName = sys.argv[2]
URLPre = "https://www.youtube.com"

oFILE = open(MetaName, "a+")

dryscrape.start_xvfb()
session = dryscrape.Session()
session.set_header('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0')
session.set_timeout('100')
session.visit(URL)
HTML = session.body()

soup = BeautifulSoup(HTML, features="html.parser")
videoBlocks = soup.find_all('a', {'class': 'ytd-playlist-video-renderer'})

for block in videoBlocks:
    youRL = URLPre + str(block['href'])
    print(youRL)
    oFILE.write(youRL + '\n')

oFILE.close()
```

Then Run:

`./utubepls.py <youtube Playlist URL> <filename>`

Then:

```
#!/bin/bash

if [ "$#" -lt 1 ];  then
        echo " "
        echo "UTube Playlist Aut0-D13r v012.3.2"
        echo "" 
        echo "Usage: $0 <plsfile>"
        echo " "
        exit
fi

PLSF=$1
while read -r URL; do 
        youtube-dl -i --no-playlist "$URL" --merge-output-format mkv --add-metadata  --download-archive archive.txt
done < <(cat $PLSF)

echo "Done."

```

Running the bash script after the python script:

`./utubeplist.sh <filename>`

**Pull request merged**
